import type {
  Client,
  Order,
  Project,
  ProjectStatus,
  Supplier,
  Profile,
} from '@/types/database'

export const DEMO_PROFILE: Profile = {
  id: 'demo-electrician',
  email: 'aziz@simchi.uz',
  full_name: 'Азиз Рахимов',
  phone: '+998 90 123 45 67',
  city: 'Ташкент',
  company_name: 'Simchi Electro',
  role: 'electrician',
  is_blocked: false,
  avatar_url: null,
  locale: 'ru',
  created_at: '2026-03-01T10:00:00Z',
  updated_at: '2026-03-20T10:00:00Z',
  deleted_at: null,
}

export const DEMO_CLIENTS: Client[] = [
  {
    id: 'c1',
    electrician_id: DEMO_PROFILE.id,
    full_name: 'Жахонгир Каримов',
    phone: '+998 91 700 11 22',
    telegram: '@jahongir_k',
    comment: 'Квартира в Яшнабаде',
    city: 'Ташкент',
    created_at: '2026-03-02T09:00:00Z',
    updated_at: '2026-03-02T09:00:00Z',
    deleted_at: null,
  },
  {
    id: 'c2',
    electrician_id: DEMO_PROFILE.id,
    full_name: 'Нилуфар Юсупова',
    phone: '+998 93 505 33 44',
    telegram: null,
    comment: 'Частный дом',
    city: 'Самарканд',
    created_at: '2026-03-05T09:00:00Z',
    updated_at: '2026-03-05T09:00:00Z',
    deleted_at: null,
  },
  {
    id: 'c3',
    electrician_id: DEMO_PROFILE.id,
    full_name: 'ООО Fresh Market',
    phone: '+998 71 200 55 66',
    telegram: '@fresh_market',
    comment: 'Магазин на Чиланзаре',
    city: 'Ташкент',
    created_at: '2026-03-08T09:00:00Z',
    updated_at: '2026-03-08T09:00:00Z',
    deleted_at: null,
  },
]

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'p1',
    electrician_id: DEMO_PROFILE.id,
    client_id: 'c1',
    title: 'Квартира 78 м² — Яшнабад',
    address: 'ул. Бабура, 45',
    city: 'Ташкент',
    object_type: 'apartment',
    work_kind: 'renovation',
    floors_count: 1,
    wiring_type: 'hidden',
    note: 'Замена проводки в 4 помещениях',
    status: 'pending_approval',
    materials_total: 8_450_000,
    works_total: 4_200_000,
    grand_total: 12_650_000,
    rooms_count: 4,
    distance_to_panel_m: 12,
    panels_count: 1,
    panel_floor: 1,
    routing_method: 'ceiling',
    spare_percent: 10,
    complexity_coefficient: 1.1,
    created_at: '2026-03-10T08:00:00Z',
    updated_at: '2026-03-22T14:00:00Z',
    deleted_at: null,
    clients: DEMO_CLIENTS[0],
  },
  {
    id: 'p2',
    electrician_id: DEMO_PROFILE.id,
    client_id: 'c2',
    title: 'Частный дом — Самарканд',
    address: 'массив Ургут, 12',
    city: 'Самарканд',
    object_type: 'private_house',
    work_kind: 'new',
    floors_count: 2,
    wiring_type: 'combined',
    note: null,
    status: 'confirmed',
    materials_total: 22_800_000,
    works_total: 11_500_000,
    grand_total: 34_300_000,
    rooms_count: 8,
    distance_to_panel_m: 18,
    panels_count: 2,
    panel_floor: 1,
    routing_method: 'wall',
    spare_percent: 12,
    complexity_coefficient: 1.25,
    created_at: '2026-03-12T08:00:00Z',
    updated_at: '2026-03-21T11:00:00Z',
    deleted_at: null,
    clients: DEMO_CLIENTS[1],
  },
  {
    id: 'p3',
    electrician_id: DEMO_PROFILE.id,
    client_id: 'c3',
    title: 'Магазин Fresh Market',
    address: 'Чиланзар-9, блок А',
    city: 'Ташкент',
    object_type: 'shop',
    work_kind: 'renovation',
    floors_count: 1,
    wiring_type: 'open',
    note: 'Витринное освещение',
    status: 'materials_ordered',
    materials_total: 15_600_000,
    works_total: 6_900_000,
    grand_total: 22_500_000,
    rooms_count: 3,
    distance_to_panel_m: 9,
    panels_count: 1,
    panel_floor: 1,
    routing_method: 'cable_channel',
    spare_percent: 8,
    complexity_coefficient: 1,
    created_at: '2026-03-14T08:00:00Z',
    updated_at: '2026-03-23T09:00:00Z',
    deleted_at: null,
    clients: DEMO_CLIENTS[2],
  },
  {
    id: 'p4',
    electrician_id: DEMO_PROFILE.id,
    client_id: 'c1',
    title: 'Офис коворкинга — черновик',
    address: 'Мирабад, 3 этаж',
    city: 'Ташкент',
    object_type: 'office',
    work_kind: 'new',
    floors_count: 1,
    wiring_type: 'hidden',
    note: 'Черновик замеров',
    status: 'draft',
    materials_total: 0,
    works_total: 0,
    grand_total: 0,
    rooms_count: 2,
    distance_to_panel_m: null,
    panels_count: 1,
    panel_floor: null,
    routing_method: null,
    spare_percent: 10,
    complexity_coefficient: 1,
    created_at: '2026-03-24T08:00:00Z',
    updated_at: '2026-03-24T16:00:00Z',
    deleted_at: null,
    clients: DEMO_CLIENTS[0],
  },
]

export const DEMO_SUPPLIERS: Supplier[] = [
  {
    id: 's1',
    owner_profile_id: null,
    name: 'ElectroMarket Tashkent',
    logo_url: null,
    description: 'Кабели, автоматы и розетки оптом',
    city: 'Ташкент',
    address: 'Сергели, склад 4',
    phone: '+998 71 150 20 20',
    telegram: '@electromarket',
    website: 'https://electromarket.uz',
    rating: 4.8,
    delivery_terms: 'Доставка по городу от 150 000 UZS',
    min_order_amount: 1_000_000,
    electrician_discount_percent: 3,
    platform_commission_percent: 3,
    verification_status: 'verified',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
    deleted_at: null,
  },
  {
    id: 's2',
    owner_profile_id: null,
    name: 'Kabel Pro',
    logo_url: null,
    description: 'Специализация на кабельной продукции',
    city: 'Ташкент',
    address: 'Юнусабад-12',
    phone: '+998 71 230 44 55',
    telegram: '@kabelpro',
    website: null,
    rating: 4.6,
    delivery_terms: 'Самовывоз / доставка 1–2 дня',
    min_order_amount: 500_000,
    electrician_discount_percent: 2,
    platform_commission_percent: 3,
    verification_status: 'verified',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
    deleted_at: null,
  },
  {
    id: 's3',
    owner_profile_id: null,
    name: 'SamElektro',
    logo_url: null,
    description: 'Поставщик для Самарканда и региона',
    city: 'Самарканд',
    address: 'ул. Регистанская, 8',
    phone: '+998 66 233 11 00',
    telegram: null,
    website: null,
    rating: 4.4,
    delivery_terms: 'По области 2–3 дня',
    min_order_amount: 800_000,
    electrician_discount_percent: 2.5,
    platform_commission_percent: 3,
    verification_status: 'verified',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
    deleted_at: null,
  },
]

export const DEMO_ORDERS: Order[] = [
  {
    id: 'o1',
    electrician_id: DEMO_PROFILE.id,
    supplier_id: 's1',
    project_id: 'p3',
    estimate_id: null,
    status: 'assembling',
    subtotal: 15_600_000,
    discount_total: 468_000,
    delivery_total: 180_000,
    commission_total: 454_000,
    grand_total: 15_312_000,
    notes: 'Срочный заказ витринного освещения',
    created_at: '2026-03-20T10:00:00Z',
    updated_at: '2026-03-22T10:00:00Z',
    deleted_at: null,
    suppliers: DEMO_SUPPLIERS[0],
  },
  {
    id: 'o2',
    electrician_id: DEMO_PROFILE.id,
    supplier_id: 's2',
    project_id: 'p2',
    estimate_id: null,
    status: 'confirmed_by_supplier',
    subtotal: 18_200_000,
    discount_total: 364_000,
    delivery_total: 250_000,
    commission_total: 535_000,
    grand_total: 18_086_000,
    notes: null,
    created_at: '2026-03-18T10:00:00Z',
    updated_at: '2026-03-19T10:00:00Z',
    deleted_at: null,
    suppliers: DEMO_SUPPLIERS[1],
  },
]

export function getHomeStats(projects: Project[]) {
  const estimatesTotal = projects.reduce((s, p) => s + p.grand_total, 0)
  const materialsOrdered = projects
    .filter((p) => p.status === 'materials_ordered' || p.status === 'completed')
    .reduce((s, p) => s + p.materials_total, 0)
  const clientSavings = Math.round(estimatesTotal * 0.028)
  const activeProjects = projects.filter(
    (p) => !['completed', 'rejected'].includes(p.status),
  ).length
  return { estimatesTotal, materialsOrdered, clientSavings, activeProjects }
}

export function filterProjects(
  projects: Project[],
  status: string,
  query: string,
): Project[] {
  return projects.filter((p) => {
    const statusOk = status === 'all' || p.status === (status as ProjectStatus)
    const q = query.trim().toLowerCase()
    const queryOk =
      !q ||
      p.title.toLowerCase().includes(q) ||
      (p.address ?? '').toLowerCase().includes(q) ||
      (p.clients?.full_name ?? '').toLowerCase().includes(q)
    return statusOk && queryOk
  })
}
